export const SMALL_SCREEN_LOWER_LIMIT = 576;
export const MEDIUM_SCREEN_LOWER_LIMIT = 768;
export const LARGE_SCREEN_LOWER_LIMIT = 992;
export const EXTRA_LARGE_SCREEN_LOWER_LIMIT = 1200;
export const EXTRA_EXTRA_LARGE_SCREEN_LOWER_LIMIT = 1400;
